# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: tf-compliance
  name: Terraform-compliance
  description: Run terrafrom-compliance
  entry: hooks/tf_compliance.sh
  language: script
